stages:
  load_data:
    cmd: python src\\load_data.py --config=parameters.yaml
    deps:
    - src\\get_data.py
    - src\\load_data.py
    - data_given\\WineQT.csv
    outs:
    - data\\raw\\wineQT.csv  