base:
  project: winequality-project
  random_state: 42
  target_col: quality

data_source:
  s3_source: data_given/WineQT.csv

load_data:
  raw_dataset_csv: data/raw/WineQT.csv

split_data:
  train_path: data/processed/train_wineQT.csv
  test_path: data/processed/test_wineQT.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      # alpha: 0.9
      # l1_ratio: 0.4
      # alpha: 0.88
      # l1_ratio: 0.42
      alpha: 0.94
      l1_ratio: 0.46
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: saved_models/model.joblib